### ISSUE TITLE
Remove setavatar command

### ISSUE THREAD

**Issue by eritbh** [eritbh/yuuko#23]
Reimplement the existing command with `http`/`https` builtin modules, having a peer dep for this is annoying.

**Comment by Skillz4Killz** [comment]
Id recommend just moving the command into a separate folder like `examples/commands/setavatar.ts`. 

It is not a crucial command that helps with bot development like how "debug" or "reload" do. The commands that are part of the framework should only be those that help with developing a bot.

If anyone does desire this command they can simply just copy it to their local folder. Most people would probably prefer to use their own dep like i would prefer to use `node-fetch`. Leaving it up to the user is probably the best way to handle it IMO.

**Comment by eritbh** [comment]
I think initially this command was a lot more useful since the Discord dev apps portal didn't have a mechanism for changing the avatar and people *had* to use commands like this one for updating the avatar of their bot. Nowadays I don't think it's much of an issue and I'd be fine dropping it. I'll put this on 2.0.

**Comment by Skillz4Killz** [comment]
This issue can be closed.

**Comment by eritbh** [comment]
weird that it wasn't closed automatically, ty
