### ISSUE TITLE
Subcommands

### ISSUE THREAD

**Issue by eritbh** [eritbh/yuuko#26]
Let commands have other commands in them. e.g. `~tag tagname` != `~tag create tagname` etc.

Some concerns:

- Should subcommands be full-blown `Command` instances, or just plain objects passed to the constructor? Or should subcommands just be done with a space in the name or something like that?
- Will we need a breaking API change to modify the constructor for this? If a command has subcommands, its `process` should be optional and should print a list of subcommands by default I think.
- some other stuff I'll write down in a bit when I get to work

TODOs:

- [ ] Plan structure/interface
- [ ] Actually implement

**Comment by Skillz4Killz** [comment]
I don't really understand the purpose of this tbh. Do subcommands do anything different from a simple switch?

```js
const [subcommand, name] = args

switch (subcommand.toLowerCase()) {
 // This would be `~tag create tagname~
  case 'create': 
  // Use switch fallthrough for subcommand aliases
  case 'c':
    return createSubcommand(whatever stuff)
  // This would be `~tag delete tagname`
    case 'delete': return deleteSubcommand(whatever stuff)
  default: 
    // This would be `tag tagname`
} 
```

What im worried about is a bit overcomplexity for something simple. If subcommands are full-blown Commands that may have massive implications on whether or not they interfere with commandForName, reloading, what about command events like `postCommands`. How would a dev then handle pre or postCommands events. A subcommand is just basically a function inside a command. How are command names and command aliases handled? There is so much overhead and maintainability costs for this imo when compared to just using a simple switch statement.

**Comment by eritbh** [comment]
Subcommands have all the posibilities of regular commands, such as permission requirements. In the example you posted, `create` and `delete` could be subcommands that required e.g. `manageMessages` permissions, while using the command without a subcommand wouldn't require that permission.

The `commandForName` system will probably have to be rethought somewhat, which is fine because I'm considering changes for how commands are stored internally regardless. If a parent command has names `a1` and `a2`, and a subcommand has names `b1` and `b2`, then it could be called with any combination of those names as long as the order is correct. This would likely be accomplished by adding a `subcommandForName` method to `Command` instances for finding subcommands, or something analogous.

**Comment by eritbh** [comment]
I think I'm going to implement this by adding a `Command#addSubcommand()` method. All the logic for resolving subcommands will be added in `Command#execute()` after the initial permission checks. This should make for a relatively intuitive system where requirements cascade nicely and subcommand aliases will be supported without the client's alias handling getting more complicated.
