### ISSUE TITLE
Command Names Casing

### ISSUE THREAD

**Issue by Skillz4Killz** [eritbh/yuuko#41]
Would it be possible to .toLowerCase() in the command handler. Some of my users prefer to use capitals and are getting frustrated they can't.

![image](https://user-images.githubusercontent.com/23035000/70113400-09aba180-1627-11ea-85d1-eb159aae635c.png)

**Comment by eritbh** [comment]
Seems reasonable, i'm sure i've thought of this before but never put it down.

This will be a breaking change, so 2.0 it is. Will need a client option to optically enable case-sensitive command matching as an upgrade step for people who don't want this.

I can work on it today or tomorrow maybe probably.™️

**Comment by ghost** [comment]
@Geo1088, is the feature implemented yet?
I have opened a pull-request concerning the feature-request, take your time and have a look at it.

**Comment by eritbh** [comment]
Done with #43, thanks again!
