### ISSUE TITLE
Feature Request: globalCommandRequirements as client option instead of assigning it after

### ISSUE THREAD

**Issue by NotReallyEight** [eritbh/yuuko#69]
A cool thing could actually be to make
```javascript
globalCommandRequirements
```
a client option instead of a property to assign later as the code will look a little bit cleaner
Making it look like something like: 
```javascript
const client = new Client({
  otheroptions: 'bla',
  globalCommandRequirements: {
    dmOnly: false,
    guildOnly: true
  }
})
```

**Comment by eritbh** [comment]
This seems like a logical request, I'm not entirely sure why global command requirements are set by a method call rather than in the constructor. Maybe when I go to implement it I'll find a reason it is the way it is, but hopefully not...

**Comment by NotReallyEight** [comment]
Oki 👍

**Comment by eritbh** [comment]
Currently we do have a client option `ignoreGlobalRequirements` which is probably not necessary anymore if we're setting the requirements from the constructor - you should be able to just do `globalCommandRequirements: someCondition ? {} : {...yourCustomRequirements}` instead. To avoid a breaking change, that option will still exist for now, but I'll deprecate it and make an issue to remove that for the next major version.
